/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2018-01-05 14:23:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/lmk/dev/java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Step16_Myproject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1515144894000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\"    content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<meta name=\"author\"      content=\"Sergey Pozhilov (GetTemplate.com)\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>Progressus - Free business bootstrap template by GetTemplate</title>\r\n");
      out.write("\t<!-- css/js -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/resource.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"home\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Fixed navbar -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/topnavbar.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- /.navbar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<header id=\"head\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<h1 class=\"lead\">AWESOME PAGE</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- /Header -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Intro -->\r\n");
      out.write("\t<div class=\"container text-center\">\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\t\t<h2 class=\"thin\">The best place to tell people why they are here</h2>\r\n");
      out.write("\t\t<p class=\"text-muted\">\r\n");
      out.write("\t\t\tThe difference between involvement and commitment is like an eggs-and-ham breakfast:<br> \r\n");
      out.write("\t\t\tthe chicken was involved; the pig was committed.\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /Intro-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- Highlights - jumbotron -->\r\n");
      out.write("\t<div class=\"jumbotron top-space\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3 class=\"text-center thin\">Reasons to use this template</h3>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-sm-6 highlight\">\r\n");
      out.write("\t\t\t\t\t<div class=\"h-caption\"><h4><i class=\"fa fa-cogs fa-5\"></i>Bootstrap-powered</h4></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"h-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque aliquid adipisci aspernatur. Soluta quisquam dignissimos earum quasi voluptate. Amet, dignissimos, tenetur vitae dolor quam iusto assumenda hic reprehenderit?</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-sm-6 highlight\">\r\n");
      out.write("\t\t\t\t\t<div class=\"h-caption\"><h4><i class=\"fa fa-flash fa-5\"></i>Fat-free</h4></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"h-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, commodi, sequi quis ad fugit omnis cumque a libero error nesciunt molestiae repellat quos perferendis numquam quibusdam rerum repellendus laboriosam reprehenderit! </p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-sm-6 highlight\">\r\n");
      out.write("\t\t\t\t\t<div class=\"h-caption\"><h4><i class=\"fa fa-heart fa-5\"></i>Creative Commons</h4></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"h-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, vitae, perferendis, perspiciatis nobis voluptate quod illum soluta minima ipsam ratione quia numquam eveniet eum reprehenderit dolorem dicta nesciunt corporis?</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-sm-6 highlight\">\r\n");
      out.write("\t\t\t\t\t<div class=\"h-caption\"><h4><i class=\"fa fa-smile-o fa-5\"></i>Author's support</h4></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"h-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, excepturi, maiores, dolorem quasi reprehenderit illo accusamus nulla minima repudiandae quas ducimus reiciendis odio sequi atque temporibus facere corporis eos expedita? </p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div> <!-- /row  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /Highlights -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- container -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<h2 class=\"text-center top-space\">Frequently Asked Questions</h2>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<h3>Which code editor would you recommend?</h3>\r\n");
      out.write("\t\t\t\t<p>I'd highly recommend you <a href=\"http://www.sublimetext.com/\">Sublime Text</a> - a free to try text editor which I'm using daily. Awesome tool!</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<h3>Nice header. Where do I find more images like that one?</h3>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tWell, there are thousands of stock art galleries, but personally, \r\n");
      out.write("\t\t\t\t\tI prefer to use photos from these sites: <a href=\"http://unsplash.com\">Unsplash.com</a> \r\n");
      out.write("\t\t\t\t\tand <a href=\"http://www.flickr.com/creativecommons/by-2.0/tags/\">Flickr - Creative Commons</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div> <!-- /row -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<h3>Can I use it to build a site for my client?</h3>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tYes, you can. You may use this template for any purpose, just don't forget about the <a href=\"http://creativecommons.org/licenses/by/3.0/\">license</a>, \r\n");
      out.write("\t\t\t\t\twhich says: \"You must give appropriate credit\", i.e. you must provide the name of the creator and a link to the original template in your work. \r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<h3>Can you customize this template for me?</h3>\r\n");
      out.write("\t\t\t\t<p>Yes, I can. Please drop me a line to sergey-at-pozhilov.com and describe your needs in details. Please note, my services are not cheap.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div> <!-- /row -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"jumbotron top-space\">\r\n");
      out.write("\t\t\t<h4>Dicta, nostrum nemo soluta sapiente sit dolor quae voluptas quidem doloribus recusandae facere magni ullam suscipit sunt atque rerum eaque iusto facilis esse nam veniam incidunt officia perspiciatis at voluptatibus. Libero, aliquid illum possimus numquam fuga.</h4>\r\n");
      out.write("     \t\t<p class=\"text-right\"><a class=\"btn btn-primary btn-large\">Learn more »</a></p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\t<!-- /container -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Social links. @TODO: replace by link/instructions in template -->\r\n");
      out.write("\t<section id=\"social\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"wrapper clearfix\">\r\n");
      out.write("\t\t\t\t<!-- AddThis Button BEGIN -->\r\n");
      out.write("\t\t\t\t<div class=\"addthis_toolbox addthis_default_style\">\r\n");
      out.write("\t\t\t\t<a class=\"addthis_button_facebook_like\" fb:like:layout=\"button_count\"></a>\r\n");
      out.write("\t\t\t\t<a class=\"addthis_button_tweet\"></a>\r\n");
      out.write("\t\t\t\t<a class=\"addthis_button_linkedin_counter\"></a>\r\n");
      out.write("\t\t\t\t<a class=\"addthis_button_google_plusone\" g:plusone:size=\"medium\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- AddThis Button END -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- /social links -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
